### ISSUE TITLE
vcd_vdc_network - Cannot create direct network

### ISSUE THREAD

**Issue by goagex** [vmware/ansible-module-vcloud-director#103]
role/play:
```yaml
- name: 'add vdc network'
  vcd_vdc_network:
    host: 'xxx'
    verify_ssl_certs: false
    user: 'userX'
    password: 'passwordX'
    state: 'present'
    org: 'SYSTEM'
    org_name: 'custorg'
    vdc_name: 'custorgvdc'
    network_name: 'vdc_network01'
    parent_network_name: 'external_network01'
    description: 'test'
    direct: true
    shared: false
```
Output/failure:
```
TASK [vcd__add_vdc_network : add vdc network] **************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false
  module_stderr: |-
    /home/jonale/.ansible/tmp/ansible-tmp-1582281981.5551946-256638038642073/AnsiballZ_vcd_vdc_network.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      import imp
    /usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vcloud.ourdomain.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      InsecureRequestWarning,
    /usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vcloud.ourdomain.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      InsecureRequestWarning,
    /usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vcloud.ourdomain.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      InsecureRequestWarning,
    Traceback (most recent call last):
      File "/home/jonale/.ansible/tmp/ansible-tmp-1582281981.5551946-256638038642073/AnsiballZ_vcd_vdc_network.py", line 114, in <module>
        _ansiballz_main()
      File "/home/jonale/.ansible/tmp/ansible-tmp-1582281981.5551946-256638038642073/AnsiballZ_vcd_vdc_network.py", line 106, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/jonale/.ansible/tmp/ansible-tmp-1582281981.5551946-256638038642073/AnsiballZ_vcd_vdc_network.py", line 49, in invoke_module
        imp.load_module('__main__', mod, module, MOD_DESC)
      File "/usr/lib/python3.7/imp.py", line 234, in load_module
        return load_source(name, filename, file)
      File "/usr/lib/python3.7/imp.py", line 169, in load_source
        module = _exec(spec, sys.modules[name])
      File "<frozen importlib._bootstrap>", line 630, in _exec
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/ansible_vcd_vdc_network_payload_3thov3cl/__main__.py", line 433, in <module>
      File "/tmp/ansible_vcd_vdc_network_payload_3thov3cl/__main__.py", line 419, in main
      File "/tmp/ansible_vcd_vdc_network_payload_3thov3cl/__main__.py", line 229, in __init__
      File "/usr/local/lib/python3.7/dist-packages/pyvcloud/vcd/vdc.py", line 64, in __init__
        "VDC initialization failed as arguments are either invalid "
    pyvcloud.vcd.exceptions.InvalidParameterException: VDC initialization failed as arguments are either invalid or None
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

**Comment by goagex** [comment]
My bad, the problem was the variables.
The module is working as expected now.
