### ISSUE TITLE
vcd_vapp_vm fails on create vm from template

### ISSUE THREAD

**Issue by larsxsamuelsson** [vmware/ansible-module-vcloud-director#134]
Been facing a problem creating VMs from templates with the vcd_vapp_vm module.
Everything is run from a Fedora Core 32 machine with python 3.8.
Have had success with multiple other of the vcloud modules on this machine, but at least this one is creating headaches :-)

The full traceback is:
Traceback (most recent call last):
  File "/home/lars/.ansible/tmp/ansible-tmp-1599660810.4829195-47537-127443624450598/AnsiballZ_vcd_vapp_vm.py", line 102, in <module>
    _ansiballz_main()
  File "/home/lars/.ansible/tmp/ansible-tmp-1599660810.4829195-47537-127443624450598/AnsiballZ_vcd_vapp_vm.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/lars/.ansible/tmp/ansible-tmp-1599660810.4829195-47537-127443624450598/AnsiballZ_vcd_vapp_vm.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.vcd_vapp_vm', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_vcd_vapp_vm_payload_jkkd2sn_/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py", line 564, in <module>
  File "/tmp/ansible_vcd_vapp_vm_payload_jkkd2sn_/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py", line 541, in main
  File "/tmp/ansible_vcd_vapp_vm_payload_jkkd2sn_/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py", line 243, in __init__
  File "/tmp/ansible_vcd_vapp_vm_payload_jkkd2sn_/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py", line 310, in get_target_resource
  File "/home/lars/.local/lib/python3.8/site-packages/pyvcloud/vcd/vdc.py", line 63, in __init__
    raise InvalidParameterException(
pyvcloud.vcd.exceptions.InvalidParameterException: VDC initialization failed as arguments are either invalid or None
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/lars/.ansible/tmp/ansible-tmp-1599660810.4829195-47537-127443624450598/AnsiballZ_vcd_vapp_vm.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/lars/.ansible/tmp/ansible-tmp-1599660810.4829195-47537-127443624450598/AnsiballZ_vcd_vapp_vm.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/lars/.ansible/tmp/ansible-tmp-1599660810.4829195-47537-127443624450598/AnsiballZ_vcd_vapp_vm.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.vcd_vapp_vm', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vcd_vapp_vm_payload_jkkd2sn_/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py\", line 564, in <module>\n  File \"/tmp/ansible_vcd_vapp_vm_payload_jkkd2sn_/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py\", line 541, in main\n  File \"/tmp/ansible_vcd_vapp_vm_payload_jkkd2sn_/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py\", line 243, in __init__\n  File \"/tmp/ansible_vcd_vapp_vm_payload_jkkd2sn_/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py\", line 310, in get_target_resource\n  File \"/home/lars/.local/lib/python3.8/site-packages/pyvcloud/vcd/vdc.py\", line 63, in __init__\n    raise InvalidParameterException(\npyvcloud.vcd.exceptions.InvalidParameterException: VDC initialization failed as arguments are either invalid or None\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by mukultaneja** [comment]
@larsxsamuelsson what is the VCD version?

**Comment by larsxsamuelsson** [comment]
@mukultaneja 10.1.2 , i thought it was contained in the 10.1. But now that i try it towards our 10.0.0.2 it seems to work fine, so it seems to be 10.1.2 that is the issue.

**Comment by mukultaneja** [comment]
@larsxsamuelsson sure, please share the playbook once which you are using to create a VM.

**Comment by larsxsamuelsson** [comment]
Sometimes, all you need is someone to ask you to give up your configs.. Then you are forced to review them.. and realized that you yourself were the culprit :P
Will close this one now since I had a type-o that i did not see for too many weeks.
