### ISSUE TITLE
vcd_vapp shows AttributeError

### ISSUE THREAD

**Issue by TheEric7** [vmware/ansible-module-vcloud-director#171]
Can't work with vcd_vapp as it throws **_AttributeError: 'NoneType' object has no attribute 'get'_** error.

Here is the full error output:
```
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_vcd_vapp_payload_fowrwlzv/ansible_vcd_vapp_payload.zip/ansible/modules/vcd_vapp.py", line 638, in <module>
  File "/tmp/ansible_vcd_vapp_payload_fowrwlzv/ansible_vcd_vapp_payload.zip/ansible/modules/vcd_vapp.py", line 615, in main
  File "/tmp/ansible_vcd_vapp_payload_fowrwlzv/ansible_vcd_vapp_payload.zip/ansible/modules/vcd_vapp.py", line 239, in __init__
AttributeError: 'NoneType' object has no attribute 'get'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vcd_vapp_payload_fowrwlzv/ansible_vcd_vapp_payload.zip/ansible/modules/vcd_vapp.py\", line 638, in <module>\n  File \"/tmp/ansible_vcd_vapp_payload_fowrwlzv/ansible_vcd_vapp_payload.zip/ansible/modules/vcd_vapp.py\", line 615, in main\n  File \"/tmp/ansible_vcd_vapp_payload_fowrwlzv/ansible_vcd_vapp_payload.zip/ansible/modules/vcd_vapp.py\", line 239, in __init__\nAttributeError: 'NoneType' object has no attribute 'get'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP **************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

And here is the simple playbook to initiate a vapp:
```
---
- name: Test
  hosts: localhost
  environment:
    env_user: my_user
    env_password: my_password
    env_host: my_host
    env_org: system
    env_api_version: 30.0
    env_verify_ssl_certs: false
  tasks:
  - name: instantiate vapp
    vcd_vapp:
      vapp_name: test_vapp_1
      template_name: PA-VM-300
      catalog_name: cat1
      vdc: test-vdc
      power_on: False
      storage_profile: Standard
      state: present
    register: output
```

**Comment by mukultaneja** [comment]
Could you please confirm if `test-vdc` is present and accessible? This exception has been thrown up from line 
https://github.com/vmware/ansible-module-vcloud-director/blob/master/modules/vcd_vapp.py#L239 and this only possible if it cant find the VDC.

**Comment by TheEric7** [comment]
Yes, the VDC is present and accessible.
I can do whatever I want via GUI.

**Comment by surfer190** [comment]
@mukultaneja is correct and I recreated the issue.

Change the `vdc` variable on the `vdc_vapp` task - with the name of your existing vdc (it must not be `test-vdc` unless that is what it is called)

```
  - name: instantiate vapp
    vcd_vapp:
      vapp_name: test_vapp_1
      template_name: PA-VM-300
      catalog_name: cat1
      **vdc: test-vdc**
      power_on: False
```

**Comment by TheEric7** [comment]
test-vdc is the actual name of my vdc.

@surfer190 did you recreate the issue by using the system account?

**Comment by surfer190** [comment]
No, I was using a tenant account.

**Comment by TheEric7** [comment]
I think that's my issue as I am using the system account and not the tenant account.
I'm closing this issue.
