### ISSUE TITLE
Can't create a new VM

### ISSUE THREAD

**Issue by phibid** [vmware/ansible-module-vcloud-director#215]
### Describe the bug

Not sure if this is a bug or if I am doing something wrong, but I am just unable to create a new VM from templace with the `vcd_vapp_vm`. I have checked the other issues, tried several combinations, but no way.

The complete stack trace:

```
fatal: [lunuxvm02 -> 10.10.10.10]: FAILED! => changed=false 
  module_stderr: |-
    Warning: Permanently added '10.10.10.10' (ECDSA) to the list of known hosts.
    /tmp/ansible_vcd_vapp_vm_payload_eeh1dtv4/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py:402: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
    Traceback (most recent call last):
      File "/tmp/ansible_vcd_vapp_vm_payload_eeh1dtv4/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py", line 387, in add_vm
      File "/tmp/ansible_vcd_vapp_vm_payload_eeh1dtv4/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py", line 363, in get_vm
      File "/usr/lib/python3.6/site-packages/pyvcloud/vcd/vapp.py", line 660, in get_vm
        raise EntityNotFoundException('Can\'t find VM \'%s\'' % vm_name)
    pyvcloud.vcd.exceptions.EntityNotFoundException: Can't find VM 'lunuxvm02'
  
    During handling of the above exception, another exception occurred:
  
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1451, in post_linked_resource
        find_link(resource, rel, media_type).href, contents,
      File "/usr/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1755, in find_link
        raise MissingLinkException(resource.get('href'), rel, media_type)
    pyvcloud.vcd.exceptions.MissingLinkException: ('https://vcenter/api/vApp/vapp-cd994781-802b-4f3c-83e6-45799b080cb7', <RelationType.RECOMPOSE: 'recompose'>, 'application/vnd.vmware.vcloud.recomposeVAppParams+xml'); href: https://vcenter/api/vApp/vapp-cd994781-802b-4f3c-83e6-45799b080cb7, rel: RelationType.RECOMPOSE, mediaType: application/vnd.vmware.vcloud.recomposeVAppParams+xml
  
    During handling of the above exception, another exception occurred:
  
    Traceback (most recent call last):
      File "/tmp/ansible_vcd_vapp_vm_payload_eeh1dtv4/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py", line 651, in main
      File "/tmp/ansible_vcd_vapp_vm_payload_eeh1dtv4/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py", line 273, in manage_states
      File "/tmp/ansible_vcd_vapp_vm_payload_eeh1dtv4/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py", line 412, in add_vm
      File "/usr/lib/python3.6/site-packages/pyvcloud/vcd/vapp.py", line 1032, in add_vms
        EntityType.RECOMPOSE_VAPP_PARAMS.value, params)
      File "/usr/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1455, in post_linked_resource
        "Operation is not supported").with_traceback(e.__traceback__)
      File "/usr/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1451, in post_linked_resource
        find_link(resource, rel, media_type).href, contents,
      File "/usr/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1755, in find_link
        raise MissingLinkException(resource.get('href'), rel, media_type)
    pyvcloud.vcd.exceptions.OperationNotSupportedException: Operation is not supported
  
    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<stdin>", line 102, in <module>
      File "<stdin>", line 94, in _ansiballz_main
      File "<stdin>", line 40, in invoke_module
      File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_vcd_vapp_vm_payload_eeh1dtv4/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py", line 665, in <module>
      File "/tmp/ansible_vcd_vapp_vm_payload_eeh1dtv4/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py", line 659, in main
      File "/tmp/ansible_vcd_vapp_vm_payload_eeh1dtv4/ansible_vcd_vapp_vm_payload.zip/ansible/module_utils/basic.py", line 2220, in fail_json
      File "/tmp/ansible_vcd_vapp_vm_payload_eeh1dtv4/ansible_vcd_vapp_vm_payload.zip/ansible/module_utils/basic.py", line 2193, in _return_formatted
      File "/tmp/ansible_vcd_vapp_vm_payload_eeh1dtv4/ansible_vcd_vapp_vm_payload.zip/ansible/module_utils/basic.py", line 420, in remove_values
      File "/tmp/ansible_vcd_vapp_vm_payload_eeh1dtv4/ansible_vcd_vapp_vm_payload.zip/ansible/module_utils/basic.py", line 397, in _remove_values_conditions
    TypeError: Value of unknown type: <class 'pyvcloud.vcd.exceptions.OperationNotSupportedException'>, Operation is not supported
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

The Ansible task executed:

```
- name: Create new VM from catalog
  vcd_vapp_vm:
    host: "{{ vcd_host }}"
    org: "{{ vcd_org }}"
    user: "{{ vcd_username }}"
    password: "{{ vcd_password }}"
    api_version: "{{ vcd_api_version }}"
    target_vm_name: "{{ vm_name }}"
    target_vapp: "{{ vcd_vapp }}"
    source_vdc: "{{ vcd_vdc }}"
    target_vdc: "{{ vcd_vdc }}"
    source_catalog_name: "{{ vcd_catalog }}"
    source_template_name: "{{ os }}"
    source_vm_name: "{{ os }}"
    hostname: "{{ vm_name }}"
    vmpassword: "{{ root_password }}"
    vmpassword_auto: "false"
    vmpassword_reset: "false"
    state: "present"
    operation: poweron
    all_eulas_accepted: "true"
    storage_profile: "{{ vcd_storage }}"
```

The API version is 34.0.

### Reproduction steps

```bash
Execute the Ansible task.
```

### Expected behavior

A new VM from the template should be created

**Comment by phibid** [comment]
Please disregard this issue. This is working, some privileges were missing.
